### ISSUE TITLE
DNSSEC key breaking recordset unmarshal

### ISSUE THREAD

**Issue by jhg03a** [vinyldns/go-vinyldns#71]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed.

### Description

When attempting to unmarshal a DS record from the VinylDNS, the algorithm field is sent as an integer, but the golang library tries to unmarshal it as a string and fails.

### Steps to Reproduce

1. Try to obtain all recordsets in a zone containing a DS record, or just the DS recordset itself that contains a keytag, alforithm, digesttype, and digest.

**Expected behavior:** [What you expect to happen]
I expect the golang library to unmarshal the struct.

**Actual behavior:** [What actually happens]
An error is returned: `json: cannot unmarshal number into Go struct field Record.algorithm of type string`

**Reproduces how often:** [What percentage of the time does it reproduce?]
Reproducible every time.

### Versions

The specific version of `go-vinyldns` you're using.
Head of master @ commit a3af7b3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by mdb** [comment]
Thanks for discovering and reporting, @jhg03a !
