### ISSUE TITLE
unsupported tag format

### ISSUE THREAD

**Issue by ldez** [vinyldns/go-vinyldns#80]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed.

### Description

the current tags (`0.9.13`, `0.9.12`, ...) don't work with the go modules system.

could you add tags `v0.9.13`, `v0.9.12`, ... ?

### Steps to Reproduce

```bash
go get github.com/vinyldns/go-vinyldns@0.9.13
```

**Expected behavior:** [What you expect to happen]

```
require (
	github.com/vinyldns/go-vinyldns v0.9.13
)
```

**Actual behavior:** [What actually happens]

```
require (
	github.com/vinyldns/go-vinyldns v0.0.0-20200917153823-148a5f6b8f14
)
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

All current versions.

### Additional Information

none.

**Comment by remerle** [comment]
Fixed in #82 and [Release v0.9.15](https://github.com/vinyldns/go-vinyldns/releases/tag/v0.9.15)
